### ISSUE TITLE
Ollama support?

### ISSUE THREAD

**Issue by dezoito** [jndiogo/sibila#1]
@jndiogo,

First of all thank you for making this public!

Do you have any plans to support Ollama as a source for models?

We could then use local models using something like:

```py
model = Models.create("ollama:llama2")
```

I understand this gets a little more complex in reality, since need some way to pass an alternate URL for the ollama server, and inference parameters (like `temperature` and an optional `system prompt`) when calling `extract()` and that would probably entail changes to `GenConf()`.

Again, thank you.

**Comment by jndiogo** [comment]
Thanks for the suggestion! More providers would be a good thing.

I did a quick search and it seems [Ollama doesn't yet support](https://github.com/ollama/ollama/blob/main/docs/openai.md) the tools request field, which would make it trivial to use the OpenAI library to access it.

This is necessary because we need to pass a JSON Schema or a grammar to constrain generation in remote models. There are PRs in Ollama to add this but it's not there yet. On the other hand, LangChain is apparently [using Ollama with OpenAI tools field](https://python.langchain.com/docs/integrations/chat/ollama_functions) - will look into it.

**Comment by dezoito** [comment]
Much appreciated.
